/**
 * A broad bank of textbook-style AP Physics C questions, each with its
 * worked answer in SI units. Unlike the eval bank these are free-response:
 * there are no choices to match against, so the fly has to actually produce
 * the number. `problem-bank.test.ts` runs every one through the freeform
 * solver.
 *
 * Values are the answer to three significant figures, using the constants on
 * the AP sheet (g = 9.8 m/s², G = 6.67×10⁻¹¹, k = 8.99×10⁹, M_earth =
 * 5.97×10²⁴ kg, R_earth = 6.37×10⁶ m, e = 1.6×10⁻¹⁹ C, m_e = 9.11×10⁻³¹ kg,
 * m_p = 1.67×10⁻²⁷ kg).
 */
export type BankCase = [text: string, value: number, unit: string];

export const PROBLEM_BANK: Record<string, BankCase[]> = {
  kinematics: [
    ["A car accelerates from rest at 3 m/s² for 8 s. How far does it travel?", 96, "m"],
    ["A ball is dropped from a height of 45 m. How long does it take to hit the ground?", 3.03, "s"],
    ["A ball is thrown straight up at 20 m/s. What is its maximum height?", 20.4, "m"],
    ["A projectile is launched at 30 m/s at an angle of 40° above the horizontal. What is its range?", 90.4, "m"],
    ["A projectile is launched at 25 m/s at 37° above the horizontal. What is its maximum height?", 11.5, "m"],
    ["A projectile is launched at 20 m/s at 30° above the horizontal. How long is it in the air?", 2.04, "s"],
    ["A car moving at 30 m/s brakes at 5 m/s². How far does it travel before stopping?", 90, "m"],
    ["A ball is thrown horizontally at 12 m/s from a cliff 20 m high. How far from the base of the cliff does it land?", 24.2, "m"],
    ["A train accelerates uniformly from 10 m/s to 30 m/s in 8 s. What distance does it cover?", 160, "m"],
    ["A stone is dropped from a bridge and hits the water 2.5 s later. How high is the bridge?", 30.6, "m"],
    ["A runner covers 400 m in 50 s. What is the runner's average speed?", 8, "m/s"],
    ["A car accelerates from 15 m/s to 25 m/s over a distance of 100 m. What is its acceleration?", 2, "m/s²"],
    ["A ball is thrown straight up at 15 m/s. How long does it take to return to the thrower's hand?", 3.06, "s"],
    ["A ball is dropped from 80 m. What is its speed just before it hits the ground?", 39.6, "m/s"],
    ["A car starts from rest and reaches 24 m/s in 6 s. What is its acceleration?", 4, "m/s²"],
    ["A ball is thrown horizontally from a 45 m cliff and lands 60 m from the base. What was its initial speed?", 19.8, "m/s"],
  ],
  newton: [
    ["A 5 kg block is pushed across a frictionless floor by a 20 N force. What is its acceleration?", 4, "m/s²"],
    ["A 10 kg block slides down a frictionless incline of 30°. What is its acceleration?", 4.9, "m/s²"],
    ["A 4 kg block slides down a 37° incline with a coefficient of kinetic friction of 0.2. What is its acceleration?", 4.33, "m/s²"],
    ["A 70 kg person stands in an elevator accelerating upward at 2 m/s². What is the normal force on the person?", 826, "N"],
    ["A 3 kg mass and a 5 kg mass hang on either side of a frictionless pulley. What is the acceleration of the system?", 2.45, "m/s²"],
    ["A 3 kg mass and a 5 kg mass hang on either side of a frictionless pulley. What is the tension in the string?", 36.8, "N"],
    ["A 2 kg block on a frictionless table is connected by a string over a pulley to a hanging 3 kg mass. What is the acceleration of the system?", 5.88, "m/s²"],
    ["A 20 kg crate is pulled across a floor by a 100 N horizontal force. The coefficient of kinetic friction is 0.3. What is the crate's acceleration?", 2.06, "m/s²"],
    ["A 1000 kg car rounds a flat curve of radius 50 m at 15 m/s. What friction force is required?", 4500, "N"],
    ["A car rounds a flat curve of radius 80 m. The coefficient of static friction is 0.5. What is the maximum speed?", 19.8, "m/s"],
    ["A 0.5 kg ball on a 1.2 m string is whirled in a vertical circle. What is the minimum speed at the top?", 3.43, "m/s"],
    ["A 5 kg block rests on a 25° incline. What is the normal force on the block?", 44.4, "N"],
    ["A 60 kg skydiver falls with a drag force of 400 N. What is the skydiver's acceleration?", 3.13, "m/s²"],
    ["A 2 kg object experiences a net force of 10 N for 3 s starting from rest. What is its final speed?", 15, "m/s"],
    ["A 70 kg person stands in an elevator accelerating downward at 3 m/s². What is the person's apparent weight?", 476, "N"],
    ["A 2 kg mass hangs at rest from a string. What is the tension in the string?", 19.6, "N"],
  ],
  energy: [
    ["A 2 kg block slides from rest down a frictionless ramp 5 m high. What is its speed at the bottom?", 9.9, "m/s"],
    ["A 0.5 kg ball is dropped from 10 m. What is its kinetic energy just before impact?", 49, "J"],
    ["A spring with k = 400 N/m is compressed 0.1 m. How much energy is stored?", 2, "J"],
    ["A 0.2 kg block is launched by a spring of constant 500 N/m compressed 0.05 m. What is the block's launch speed?", 2.5, "m/s"],
    ["A 50 N force pushes a crate 8 m along the floor at an angle of 60° to the displacement. How much work is done?", 200, "J"],
    ["A 1500 kg car accelerates from rest to 20 m/s. How much work is done on it?", 300000, "J"],
    ["A 60 kg student climbs a 4 m staircase in 3 s. What is the student's power output?", 784, "W"],
    ["A 3 kg block moving at 4 m/s slides to rest on a rough surface with coefficient of kinetic friction 0.25. How far does it slide?", 3.27, "m"],
    ["A roller coaster car starts from rest at a height of 40 m. What is its speed at a height of 15 m?", 22.1, "m/s"],
    ["An engine delivers 3000 W of power to a car moving at 15 m/s. What force does the engine exert?", 200, "N"],
    ["A pendulum bob is released from rest at a height of 0.5 m above its lowest point. What is its speed at the lowest point?", 3.13, "m/s"],
    ["What is the gravitational potential energy of a 4 kg object 6 m above the ground?", 235, "J"],
    ["A 0.1 kg ball is thrown upward with 20 J of kinetic energy. How high does it rise?", 20.4, "m"],
    ["A 2 kg block moving at 6 m/s compresses a spring of constant 800 N/m. What is the maximum compression?", 0.3, "m"],
    ["A 1000 kg car moving at 20 m/s brakes to rest. How much work do the brakes do?", 200000, "J"],
  ],
  momentum: [
    ["A 0.15 kg baseball moving at 40 m/s is hit back at 50 m/s. What is the magnitude of the impulse?", 13.5, "kg·m/s"],
    ["A 1200 kg car moving at 20 m/s collides and sticks to a stationary 800 kg car. What is their speed after the collision?", 12, "m/s"],
    ["A 0.01 kg bullet is fired at 400 m/s into a 2 kg block at rest and embeds in it. What is the speed of the block afterward?", 1.99, "m/s"],
    ["A 60 kg skater at rest throws a 2 kg ball at 15 m/s. What is the skater's recoil speed?", 0.5, "m/s"],
    ["A 4 kg rifle fires a 0.02 kg bullet at 600 m/s. What is the recoil speed of the rifle?", 3, "m/s"],
    ["A 2 kg cart moving at 3 m/s collides elastically with a 1 kg cart at rest. What is the velocity of the second cart after the collision?", 4, "m/s"],
    ["A 0.5 kg ball's velocity changes from 10 m/s to 4 m/s in 0.2 s. What is the magnitude of the average force on it?", 15, "N"],
    ["A 1000 kg car moving at 30 m/s is brought to rest in 6 s. What is the magnitude of the average braking force?", 5000, "N"],
    ["A 3 kg object moves at 5 m/s. What is its momentum?", 15, "kg·m/s"],
    ["A 0.01 kg bullet embeds in a 1.99 kg ballistic pendulum, which then rises 0.2 m. What was the bullet's speed?", 396, "m/s"],
    ["A 5 kg block moving at 6 m/s collides and sticks to a 3 kg block moving in the same direction at 2 m/s. What is their common velocity?", 4.5, "m/s"],
    ["A 2 kg mass is at x = 0 m and a 6 kg mass is at x = 4 m. Where is the center of mass?", 3, "m"],
    ["A 1200 kg car moving at 20 m/s collides and sticks to a stationary 800 kg car. How much kinetic energy is lost?", 96000, "J"],
    ["A 50 N force acts on an object for 0.4 s. What impulse does it deliver?", 20, "kg·m/s"],
  ],
  rotation: [
    ["A wheel starts from rest and accelerates at 2 rad/s² for 5 s. What is its angular velocity?", 10, "rad/s"],
    ["A wheel starts from rest and accelerates at 4 rad/s² for 3 s. Through what angle does it turn?", 18, "rad"],
    ["A solid disk has a mass of 4 kg and a radius of 0.5 m. What is its moment of inertia?", 0.5, "kg·m²"],
    ["A 20 N force is applied tangentially to the rim of a wheel of radius 0.3 m. What is the torque?", 6, "N·m"],
    ["A torque of 12 N·m acts on a flywheel with a moment of inertia of 3 kg·m². What is its angular acceleration?", 4, "rad/s²"],
    ["A flywheel with a moment of inertia of 2 kg·m² spins at 10 rad/s. What is its rotational kinetic energy?", 100, "J"],
    ["A flywheel with a moment of inertia of 2 kg·m² spins at 10 rad/s. What is its angular momentum?", 20, "kg·m²/s"],
    ["A skater with a moment of inertia of 4 kg·m² spinning at 2 rad/s pulls in her arms, reducing her moment of inertia to 1.6 kg·m². What is her new angular velocity?", 5, "rad/s"],
    ["A solid sphere rolls without slipping from rest down an incline of height 2 m. What is its speed at the bottom?", 5.29, "m/s"],
    ["A hoop rolls without slipping from rest down an incline of height 1.5 m. What is its speed at the bottom?", 3.83, "m/s"],
    ["A solid cylinder rolls without slipping down a 30° incline. What is its acceleration?", 3.27, "m/s²"],
    ["A uniform rod of mass 3 kg and length 2 m rotates about one end. What is its moment of inertia?", 4, "kg·m²"],
    ["A uniform rod of mass 3 kg and length 2 m rotates about its center. What is its moment of inertia?", 1, "kg·m²"],
    ["A wheel of radius 0.4 m rotates at 5 rad/s. What is the linear speed of a point on its rim?", 2, "m/s"],
    ["A solid sphere has a mass of 5 kg and a radius of 0.2 m. What is its moment of inertia?", 0.08, "kg·m²"],
    ["A disk with a moment of inertia of 0.5 kg·m² spinning at 12 rad/s is brought to rest by a constant torque in 4 s. What is the magnitude of the torque?", 1.5, "N·m"],
    ["A wheel rotating at 20 rad/s slows uniformly to rest in 5 s. What is the magnitude of its angular acceleration?", 4, "rad/s²"],
    ["A hoop has a mass of 2 kg and a radius of 0.5 m. What is its moment of inertia about its axis?", 0.5, "kg·m²"],
  ],
  shm: [
    ["A 0.5 kg mass on a spring of constant 200 N/m oscillates. What is its period?", 0.314, "s"],
    ["A simple pendulum has a length of 1.5 m. What is its period?", 2.46, "s"],
    ["A mass on a spring oscillates with amplitude 0.1 m and angular frequency 5 rad/s. What is its maximum speed?", 0.5, "m/s"],
    ["A mass on a spring oscillates with amplitude 0.1 m and angular frequency 5 rad/s. What is its maximum acceleration?", 2.5, "m/s²"],
    ["A 2 kg mass on a spring of constant 50 N/m oscillates with amplitude 0.2 m. What is the total energy?", 1, "J"],
    ["A 2 kg mass on a spring of constant 50 N/m oscillates with amplitude 0.2 m. What is its maximum speed?", 1, "m/s"],
    ["A pendulum has a period of 2 s. What is its length?", 0.993, "m"],
    ["A 0.25 kg mass on a spring oscillates with a period of 0.5 s. What is the spring constant?", 39.5, "N/m"],
    ["A mass on a spring oscillates at a frequency of 4 Hz. What is its angular frequency?", 25.1, "rad/s"],
    ["A 0.4 kg mass is attached to a spring of constant 160 N/m. What is the frequency of oscillation?", 3.18, "Hz"],
    ["A 1 kg mass on a spring of constant 100 N/m oscillates with amplitude 0.3 m. What is its speed when the displacement is 0.1 m?", 2.83, "m/s"],
    ["A 0.5 kg mass on a spring of constant 200 N/m oscillates. What is its angular frequency?", 20, "rad/s"],
    ["A 2 kg mass on a spring of constant 50 N/m oscillates with amplitude 0.2 m. What is its maximum acceleration?", 5, "m/s²"],
  ],
  gravitation: [
    ["What is the gravitational force between two 1000 kg masses 2 m apart?", 1.67e-5, "N"],
    ["A satellite orbits Earth at a radius of 7.0×10⁶ m. What is its orbital speed?", 7540, "m/s"],
    ["What is the escape speed from the surface of Earth?", 11200, "m/s"],
    ["A planet has a mass of 6.0×10²⁴ kg and a radius of 6.4×10⁶ m. What is the acceleration due to gravity at its surface?", 9.77, "m/s²"],
    ["A satellite orbits Earth at a radius of 4.22×10⁷ m. What is its orbital period?", 86300, "s"],
    ["What is the gravitational potential energy of a 500 kg satellite at a distance of 7.0×10⁶ m from Earth's center?", -2.84e10, "J"],
    ["A 70 kg astronaut stands on the Moon, where g is 1.62 m/s². What is the astronaut's weight?", 113, "N"],
    ["Two masses of 5 kg and 10 kg are 0.5 m apart. What is the gravitational force between them?", 1.33e-8, "N"],
    ["A planet orbits a star of mass 2.0×10³⁰ kg at a radius of 1.5×10¹¹ m. What is its orbital period?", 3.16e7, "s"],
    ["What is the total energy of a 500 kg satellite in a circular orbit of radius 7.0×10⁶ m around Earth?", -1.42e10, "J"],
    ["A planet has a mass of 6.0×10²⁴ kg and a radius of 6.4×10⁶ m. What is the escape speed from its surface?", 11200, "m/s"],
  ],
  electrostatics: [
    ["Two charges of 3 μC and 5 μC are 0.2 m apart. What is the force between them?", 3.37, "N"],
    ["What is the electric field 0.5 m from a 4 μC point charge?", 143840, "N/C"],
    ["What is the electric potential 0.3 m from a 2 μC point charge?", 59933, "V"],
    ["A 2 μC charge is placed in a uniform electric field of 500 N/C. What force acts on it?", 0.001, "N"],
    ["An electron is accelerated from rest through a potential difference of 100 V. What is its final speed?", 5.93e6, "m/s"],
    ["Two parallel plates 0.02 m apart have a potential difference of 100 V. What is the electric field between them?", 5000, "N/C"],
    ["What is the potential energy of two charges of 2 μC and 3 μC separated by 0.1 m?", 0.539, "J"],
    ["An electron is in a uniform electric field of 2000 N/C. What is its acceleration?", 3.51e14, "m/s²"],
    ["How much work is required to move a 3 μC charge through a potential difference of 12 V?", 3.6e-5, "J"],
    ["A sphere of radius 0.1 m carries a charge of 5 nC uniformly on its surface. What is the electric field at a distance of 0.3 m from its center?", 499, "N/C"],
    ["A proton is accelerated from rest through a potential difference of 500 V. What is its kinetic energy?", 8e-17, "J"],
    ["A proton is released from rest in a uniform electric field of 1000 N/C. What is the force on it?", 1.6e-16, "N"],
  ],
  capacitors: [
    ["A 10 μF capacitor is connected to a 12 V battery. How much charge is stored?", 1.2e-4, "C"],
    ["A 4 μF capacitor is charged to 50 V. How much energy is stored?", 0.005, "J"],
    ["A 2 μF and a 3 μF capacitor are connected in parallel. What is the equivalent capacitance?", 5e-6, "F"],
    ["A 6 μF and a 3 μF capacitor are connected in series. What is the equivalent capacitance?", 2e-6, "F"],
    ["A parallel plate capacitor has plate area 0.02 m² and separation 0.001 m. What is its capacitance?", 1.77e-10, "F"],
    ["A capacitor stores 60 μC of charge at 12 V. What is its capacitance?", 5e-6, "F"],
    ["A 100 μF capacitor stores 0.5 J of energy. What is the voltage across it?", 100, "V"],
    ["A 5 μF capacitor is filled with a dielectric of constant 3. What is the new capacitance?", 1.5e-5, "F"],
    ["A 2 μF capacitor carries a charge of 40 μC. How much energy is stored?", 4e-4, "J"],
    ["A 6 μF and a 3 μF capacitor are connected in series across an 18 V battery. What is the charge on each capacitor?", 3.6e-5, "C"],
    ["A 20 μF capacitor holds 100 μC of charge. What is the voltage across it?", 5, "V"],
  ],
  circuits: [
    ["A 12 V battery is connected to a 4 Ω resistor. What is the current?", 3, "A"],
    ["A 6 Ω and a 12 Ω resistor are connected in parallel. What is the equivalent resistance?", 4, "Ω"],
    ["A 9 V battery is connected to a 3 Ω and a 6 Ω resistor in series. What is the current?", 1, "A"],
    ["A 2 A current flows through a 5 Ω resistor. How much power is dissipated?", 20, "W"],
    ["A battery with an emf of 12 V and an internal resistance of 0.5 Ω is connected to a 5.5 Ω resistor. What is the terminal voltage?", 11, "V"],
    ["A 100 Ω resistor and a 50 μF capacitor are connected in series. What is the time constant?", 0.005, "s"],
    ["A 10 μF capacitor charges through a 1000 Ω resistor from a 12 V battery. What is the voltage across the capacitor after 0.01 s?", 7.59, "V"],
    ["A 60 W bulb operates at 120 V. What is its resistance?", 240, "Ω"],
    ["A 60 W bulb operates at 120 V. What current does it draw?", 0.5, "A"],
    ["A 12 V battery is connected to a 2 Ω and a 4 Ω resistor in series. What is the voltage across the 4 Ω resistor?", 8, "V"],
    ["A 1500 W heater runs for 2 hours. How much energy does it use?", 1.08e7, "J"],
    ["A 12 V battery is connected across a 6 Ω and a 3 Ω resistor in parallel. What is the total power dissipated?", 72, "W"],
    ["A 10 μF capacitor charged to 12 V discharges through a 1000 Ω resistor. What is the initial current?", 0.012, "A"],
    ["A 3 A current flows for 20 s. How much charge passes?", 60, "C"],
    ["A 10 μF capacitor charged to 12 V discharges through a 1000 Ω resistor. What is the voltage across the capacitor after 0.02 s?", 1.62, "V"],
  ],
  magnetism: [
    ["A proton moves at 2.0×10⁶ m/s perpendicular to a 0.5 T magnetic field. What is the magnetic force on it?", 1.6e-13, "N"],
    ["A wire 0.5 m long carries 3 A perpendicular to a 0.2 T field. What is the force on the wire?", 0.3, "N"],
    ["A long straight wire carries 10 A. What is the magnetic field 0.05 m from the wire?", 4e-5, "T"],
    ["An electron moves at 3.0×10⁶ m/s perpendicular to a 0.01 T magnetic field. What is the radius of its path?", 1.71e-3, "m"],
    ["A solenoid has 2000 turns per meter and carries 3 A. What is the magnetic field inside?", 7.54e-3, "T"],
    ["Two parallel wires 0.1 m apart each carry 5 A. What is the force per unit length between them?", 5e-5, "N/m"],
    ["A proton moves in a circle in a 0.2 T magnetic field. What is its cyclotron period?", 3.28e-7, "s"],
    ["A velocity selector has an electric field of 3000 N/C and a magnetic field of 0.05 T. What speed passes through undeflected?", 60000, "m/s"],
    ["A circular loop of radius 0.1 m carries 2 A. What is the magnetic field at its center?", 1.26e-5, "T"],
    ["A 50-turn coil of area 0.02 m² carries 2 A in a 0.3 T field. What is the maximum torque on it?", 0.6, "N·m"],
    ["A solenoid of length 0.5 m has 1000 turns and carries 2 A. What is the magnetic field inside?", 5.03e-3, "T"],
    ["A 2 μC charge moves at 500 m/s perpendicular to a 0.4 T magnetic field. What is the force on it?", 4e-4, "N"],
  ],
  induction: [
    ["A loop of area 0.05 m² is in a magnetic field of 0.4 T perpendicular to the loop. What is the magnetic flux?", 0.02, "Wb"],
    ["The flux through a 100-turn coil changes by 0.03 Wb in 0.1 s. What is the induced emf?", 30, "V"],
    ["A 0.5 m rod moves at 4 m/s perpendicular to a 0.3 T field. What is the induced emf?", 0.6, "V"],
    ["A 0.5 m rod moves at 4 m/s perpendicular to a 0.3 T field and is connected to a 2 Ω resistor. What is the induced current?", 0.3, "A"],
    ["A 2 H inductor carries 3 A. How much energy is stored?", 9, "J"],
    ["A 0.2 H inductor and a 10 Ω resistor are in series. What is the time constant?", 0.02, "s"],
    ["The current in a 0.4 H inductor changes at 5 A/s. What is the induced emf?", 2, "V"],
    ["A coil with 200 turns and area 0.01 m² is in a magnetic field that changes from 0.1 T to 0.5 T in 0.2 s. What is the induced emf?", 4, "V"],
    ["A transformer has 100 primary turns and 500 secondary turns. The primary voltage is 120 V. What is the secondary voltage?", 600, "V"],
    ["An LC circuit has a 2 mH inductor and a 5 μF capacitor. What is its angular frequency?", 10000, "rad/s"],
    ["A 12 V battery is connected to a 4 Ω resistor and a 2 H inductor in series. What is the final steady-state current?", 3, "A"],
    ["A 12 V battery is connected to a 6 Ω resistor and a 3 H inductor in series. What is the current after 0.5 s?", 1.26, "A"],
    ["A solenoid has 500 turns, a length of 0.2 m and a cross-sectional area of 0.001 m². What is its inductance?", 1.57e-3, "H"],
    ["A generator coil of 100 turns and area 0.05 m² rotates at 60 rad/s in a 0.2 T field. What is the peak emf?", 60, "V"],
  ],
};
